/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

// class App {
//     val greeting: String
//         get() {
//             return "Hello World!"
//         }
// }

// fun main() {
//     println(App().greeting)
// }

import javax.swing.JFrame
import javax.swing.JLabel
import javax.swing.SwingUtilities

fun createAndShowGUI() {
    JFrame("Hello Kotlin Swing").apply {
        defaultCloseOperation = JFrame.EXIT_ON_CLOSE
        setSize(400, 300)
        setLocationRelativeTo(null)
        add(JLabel("Hello from Kotlin + Swing!", JLabel.CENTER))
        isVisible = true
    }
}

fun main() {
    SwingUtilities.invokeLater(::createAndShowGUI)
}
